### ISSUE TITLE
Cannot find module '@ffprobe-installer/linux-x64/ffprobe'

### ISSUE THREAD

**Issue by xts-bit** [SavageCore/node-ffprobe-installer#274] opened 2023-10-18 08:20 UTC
While deploying code on Vercel this package gives this error, using node 18 which is the latest version of @ffprobe-installer/ffprobe, However, it works fine on my local machine. 

My Code:
```
import { path as ffprobePath } from '@ffprobe-installer/ffprobe';

router.get("/get-ffprobe", async (req, res) => {
    res.status(200).json({ ffprobePath })
})
```
Error:
```
Cannot find module '@ffprobe-installer/linux-x64/ffprobe'
Require stack:
- /var/task/node_modules/@ffprobe-installer/ffprobe/index.js
Did you forget to add it to "dependencies" in `package.json`?
```

**Comment by xts-bit** [comment] 2023-10-20 07:52
@SavageCore can you help?

**Comment by jcham** [comment] 2023-10-26 09:56
I'm seeing this same problem also.

**Comment by xts-bit** [comment] 2023-10-30 14:17
@jcham Did you fix?

**Comment by antti-manninen-vmv** [comment] 2023-11-17 09:03
I had this too. It was most likely caused by bug in npm cli. node_modules needs to be removed before recreating package-lock.json.

https://github.com/npm/cli/issues/4828

**Comment by SavageCore** [comment] 2024-07-27 03:26
Looks like @antti-manninen-vmv has the "fix". Closing.

**Closed by SavageCore** 2024-07-27 03:26 UTC
