### ISSUE TITLE
Command was killed with SIGSEGV

### ISSUE THREAD

**Issue by azickri** [SavageCore/node-ffprobe-installer#236] opened 2022-12-17 14:13 UTC
Hello, i was trying execa with ffprobe for get video meta data.
And i get response error **Command was killed with SIGSEGV**. Like in image.

Any solving from this error?

![image](https://user-images.githubusercontent.com/45684749/208244526-d4ddfb87-9e1b-487c-ae7b-bc0306585d91.png)

-------

Spec VM:
- Ubuntu 22.04 LTS
- RAM 4GB
- Disk 20GB
- Node 14.18.2

-------

My Code:

```ts
import * as execa from 'execa';
import * as ffprobe from '@ffprobe-installer/ffprobe';

private async isValidDuration(videoUrl: string) {
  try {
    if (!videoUrl) return true;

    const params = ['-v', 'error', '-show_format', '-show_streams'];
    const { stdout } = await execa(ffprobe.path, [...params, videoUrl]);

    const duration = stdout.match(/duration="?(\d*\.\d*)"?/)[1];

    if (Number(duration) > 60) {
      return false;
    }

    return true;
  } catch (_) {
    return true;
  }
}
```

**Comment by dyc3** [comment] 2023-07-30 13:51
Duplicate of #121

**Closed** 2024-07-27 03:26 UTC
